- metadata.rb
- providers/tentacle.rb
- resources/tentacle.rb
Allows the resource to not update if old versions are found.
> Allow an option so chef does not downgrade tentacle versions

- README.md
- metadata.rb
- providers/tentacle.rb
- resources/tentacle.rb
- test/cookbooks/verify-octo/attributes/default.rb
- test/cookbooks/verify-octo/recipes/tentacle.rb
- Allow tentacle to generate cert per machine so it does not change on reconfigure
- Split remove into uninstall and remove
- Remove action now only removes an instance
> Cleanup tentacle resources and change remove functionality

- .kitchen.yml
- resources/tentacle.rb
- Added chef_omnibus_version to 12.4.1 to make sure this is tested
- Fixes #17
> Remove lazy loaded values to fix chef-clients < 12.5

- README.md
- metadata.rb
- providers/tentacle.rb
- resources/tentacle.rb
Adds firewall for tentacle
Since polling tentacles don't need the firewall opened, it only applies to listening tentacles. 
Defaults to 'false'. 
TODO
False is safer for existing cookbook users, but is bound to trip up some new users. I've added a new section to the readme making this more obvious. 
Because this is an attribute, some users might have `default['octopus']` while others would have `default['my-octopus']` in their wrapper cookbook
```
default['my-octopus']['tentacle']['instance']['polling']
default['octopus']['tentacle']['instance']['manage_firewall'] = true
```
> Add ability for the tentacle resource to setup firewall rule for listening tentacles

- CHANGELOG.md
- chefignore
- metadata.rb
- tasks/changelog.rake
- Bump to version 0.6.0
- Generate changelog
- Add more files to chefignore
- Change the rake task changelog generation to exclude issues
> Updates before publish 0.6.0

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Rakefile
- spec/spec_helper.rb
- spec/unit/lib_shared_spec.rb
- spec/unit/lib_tentacle_spec.rb
- Added new rake task to run rspec
- Included rspec in Gemfile as dependency
> Add unit test to validate library assumptions

- providers/tentacle.rb
Adds an extra restart service notification on the 'register' resource, hopefully fixing #55 
Chef is smart enough to batch up all delayed notifications of the same type so this wont cause the service to restart twice.
> Restarts tentacle service when registering

- providers/tentacle.rb
Fixes the regression that 4f788e299a3aae4b96610dcd8ced863640aa40fe introduced in #55 
Also fixes #55 so tentacles no longer require manual restarts before health checks pass. 
```ruby
* octopus_deploy_tentacle[Tentacle] action configure
* windows_firewall_rule[Octopus Deploy Tentacle] action create (skipped due to only_if)
* octopus_deploy_tentacle[Tentacle] action install[2016-08-18T00:01:28+00:00] WARN: Please use the package resource available in Chef Client 12.6.
windows_package will be removed in the next major version release
of the Windows cookbook.
* remote_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/octopus-tentacle.msi] action create (up to date)
* windows_package[Octopus Deploy Tentacle] action install (up to date)
(up to date)
* directory[C:\Octopus] action create …
```
> Fixes regression created in #55

- libraries/shared.rb
- spec/unit/lib_shared_spec.rb
If `option_list` function in libraries/shared.rb is given a non existant attribute, it will cause chef run to fail. 
By allowing option_list to be given nil parameters, it allows optional attributes to be defined. (e.g tenant and tentanttag which will be arriving in another pull request). 
#59
> Fix option_list methods handling of nils

- README.md
- providers/tentacle.rb
- resources/tentacle.rb
Allows cookbook to add a machine to a tenant or add tenant tags
I've manually tested this. Not sure how to automate testing this.
> Adds tenant and tentanttag support

- README.md
- providers/tentacle.rb
- resources/tentacle.rb
This allows multiple environments for a tentacle
> Allow multiple environments when registering tentacles

- metadata.rb
This changes the cookbook pinning from pessimistic pinning.
> Loosen up dependency version locking

- providers/server.rb
The delayed restart when a service is configured was causing issues
because the service would be started, then restarted shortly after.
This removes that restart which is unncessesary anyway. Fixes #82
> Removes the Server resources delayed restart

- metadata.rb
Now that cookbook uses custom resources, make clear that this requires chef 12.5.0
> Adds chef_version requirement to metadata.rb

- metadata.rb
Should have bumped the chef version requirement to 12.6.0 since that is the version that the windows_package resource was moved to core
>WARN: Please use the package resource available in Chef Client 12.6. windows_package will be removed in the next major version release
> Bump chef_version in metadata to 12.6.0

- Berksfile
- metadata.rb
Resolves issue #29 
Bump windows cookbook version now that `windows_package` is part of chef 12. 
Windows cookbook 3.0.x no longer includes windows_package resource. 
I intentionally didn't upgrade to 3.1.x since that version of the windows cookbook requires chef 12.7.x
The `windows_zipfile` has no breaking changes so there should be no change in behavior. 
https://github.com/chef-cookbooks/windows/blob/master/CHANGELOG.md
> Bump windows cookbook dependency

- README.md
- libraries/tentacle.rb
- resources/tentacle.rb
- spec/unit/lib_tentacle_spec.rb
- test/cookbooks/octopus-deploy-test/attributes/default.rb
- test/cookbooks/octopus-deploy-test/recipes/tentacle.rb
This allows you to override the installer url instead of just using the version on the octopus deploy download pages.
[Describe what this change achieves along with any notes about the change that are relevant]
[List any existing issues this PR resolves]
> Add tentacle install_url to override default installer url

- README.md
Installing sqlexpress with chef is a dangerous path full of pain and suffering. Removing all suggestions of how chef could manage installing sqlexpress. 
resolves https://github.com/cvent/octopus-deploy-cookbook/issues/119
> Correct readme database instructions

- libraries/shared.rb
- resources/tentacle.rb
- spec/unit/lib_shared_spec.rb
There was a bug introduced in v0.13.0
#134
> Update to fix an issue with option_list not being able to support one option

- .gitignore
- Gemfile
- Gemfile.lock
- libraries/tentacle.rb
- resources/tentacle.rb
- resources/tools.rb
- spec/unit/lib_tentacle_spec.rb
This PR disables the proxy setting recently added to the Tentacle.
If proxy settings are required, this will need to be added to the `octopus_deploy_tentacle` resource
None
- N/A -  New functionality has been documented in the README.
> Disable tentacle proxy

- resources/tentacle.rb
- test/cookbooks/octopus-deploy-test/recipes/tentacle.rb
Currently, the `import-certificate` command passes the `cert_file` parameter in without quotes - which causes powershell errors if the certificate lives in a directory that contains spaces (example: `C:\Program Files\Tentacle`). Quoting the path (as is done elsewhere in the resource) fixes this problem. Also switch to using the full argument name, which seems to be the standard for most other arguments.
This may be an issue in other places, like `libraries/server_scripts.rb`.
Unsure if the test change is necessary - happy to remove it if you think it's overkill 🙂 
N/A
> Escape spaces in certificate file

- CHANGELOG.md
- Gemfile.lock
- metadata.rb
- resources/tentacle.rb
With the newer version of the tentacle, it demands creating the instance before creating the cert. Hence switching the sequence
When registering new windows deployment targets with Octo, the script started failing as it was expecting the instance to be created before the tentacle cert.
> compatibility-tentacle-5.0.13
