metadata.rb, providers/tentacle.rb
In the current state if we reconfigure a tentacle we will not restart the tentacle so we will still be running the old configuration
=> Make sure that the services is restarted if we configure or reconfigure the tentacle

.kitchen.appveyor.yml, .travis.yml, Gemfile, README.md, appveyor.yml
Overall just add some more automated testing for fun.
=> Add appveyor for builds so that we can test converges

.gitignore, .kitchen.yml, .rubocop.yml, libraries/server.rb, metadata.rb, providers/server.rb, resources/server.rb, test/cookbooks/verify-octo/recipes/audit_server.rb, test/cookbooks/verify-octo/recipes/server.rb
=> Add service configuration resource

metadata.rb, providers/server.rb, test/cookbooks/verify-octo/recipes/audit_server.rb, test/cookbooks/verify-octo/recipes/server.rb
=> Fix issue with notifying service to restart when its disabled!

.codeclimate.yml, README.md
- Add to readme and update other labels to be clear
- Closes #11
=> Add codeclimate config for project

libraries/shared.rb, providers/tentacle.rb
=> fixes fancy_bool

libraries/shared.rb, providers/tentacle.rb, spec/unit/lib_shared_spec.rb
- Move install parameters into a library
- Fixes #51
=> Change tentacle install parameters to be more quiet

LICENSE, README.md
Fix a bad link in the README file
Update copyright in LICENSE
N/A
N/A
=> Update license copyright to follow company guidelines

README.md
http://help.octopusdeploy.com/discussions/problems/47803-could-not-find-tag-foo-on-octopus-server
=> clarifies tenant tag grouping in readme

README.md
Capitalizes the word Tentacle throughout the readme
NA
NA
Capitalized Tentacle where appropriate (I do this internally too)
=> Update README.md with capitalization

.kitchen.yml, metadata.rb, providers/tools.rb, resources/tools.rb, test/cookbooks/octopus-deploy-test/recipes/tools.rb, test/integration/tools/tools_spec.rb
Added a way to install octo tools to disk.
=> Add tools resource to allow installing of octopus deploy tools

README.md
Adds some documentation for the octopus_deploy_tools resource
Closes #78
=> Add documentation for the new tools resource

.kitchen.yml, providers/server.rb, resources/server.rb
The debug parameter lets powershell not run as sensitive
Closes #80
=> This adds a debug parameter to the server resource

appveyor.yml
Some of the appveyor configs were in the UI and not the project, went ahead and moved them entirely into the project
=> Add all appveyor configs into the repos project config

providers/server.rb, resources/server.rb, test/cookbooks/octopus-deploy-test/attributes/default.rb, test/cookbooks/octopus-deploy-test/recipes/server.rb
- Remove debug server attribute
- Closes #87
=> Use sensitive attribute for server resource instead of debug

.gitignore, Gemfile, Gemfile.lock, spec/spec_helper.rb
Adding unit test code coverage reporting to the project
=> Add unit test coverage results to the project

Gemfile, Gemfile.lock, libraries/shared.rb, spec/spec_helper.rb, spec/unit/lib_server_spec.rb, spec/unit/lib_shared_spec.rb, spec/unit/lib_tentacle_spec.rb
Add 100% coverge from unit tests
=> Update unit tests to get 100% converge

README.md
Adding more comprehensive examples to help those building octopus from scratch.
=> Adds more complete server example

README.md
=> Update readme to clarify server admin_user property

.kitchen.appveyor.yml, .kitchen.yml, appveyor.yml, metadata.rb, test/cookbooks/octopus-deploy-test/attributes/default.rb, test/cookbooks/octopus-deploy-test/recipes/server.rb
Fix some of the issues @spuder brought up about the cookbook not actually connecting to a database and running.
=> Update appveyor testing to actually use a database

README.md, resources/server.rb
=> Adds default node name for server resource

README.md, resources/server.rb
=> Validate connection_string in configure service resource

README.md
=> Add warning on database automation

README.md, resources/tentacle.rb, test/cookbooks/octopus-deploy-test/attributes/default.rb, test/cookbooks/octopus-deploy-test/recipes/tentacle.rb
=> Allow tentacle to run as untenanted

TESTING.md
=> Add testing documentation for supermarket

CONTRIBUTING.md
=> Add contributing documentation for supermarket

.kitchen.yml, libraries/server_scripts.rb, libraries/template_scripts.rb, resources/server.rb, spec/spec_helper.rb, spec/unit/lib_server_scripts_spec.rb, spec/unit/lib_server_spec.rb, spec/unit/lib_template_scripts_spec.rb
Extracting out the scripts into an ERB template so its easier to work with.  We need to be able to support 4.0 and 3.0 logic for configuring items.  This will allow is to check individual features easier.
=> Move the server scripts into a library generated by ERB

appveyor.yml
Updating the testing framework to include the latest version of chefdk
=> Update chefdk version install in appveyor to 3.8.14
